import {
  NODE_ENV,
  RESEND_API_KEY,
  SEND_EMAIL,
  UPSTASH_REDIS_REST_TOKEN,
  UPSTASH_REDIS_REST_URL,
} from "astro:env/server";

export const env = {
  NODE_ENV,
  RESEND_API_KEY,
  SEND_EMAIL,
  UPSTASH_REDIS_REST_TOKEN,
  UPSTASH_REDIS_REST_URL,
} as const;
